In [5]:
%matplotlib inline
%reload_ext autoreload
%autoreload 2

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
a = [1,2,3,4]
st = 'test'

In [8]:
#mengubah ke dalam bentuk array

ar = [1,2,3]
nr = np.array(ar)
nr

array([1, 2, 3])

In [7]:
#mengalikan nilai yang ada dalam array

nr * 2

array([2, 4, 6])

In [10]:
#mengurangi nilai per index dalam array

nr - 2

array([-1,  0,  1])

In [12]:
#membuat array dalam array

nra = np.array([
    [1,2,3],
    [2,3,1],
    [1,1,1]
])
nra

array([[1, 2, 3],
       [2, 3, 1],
       [1, 1, 1]])

In [13]:
#mengetahui dimensi dari sebuah array

nra.shape

(3, 3)

In [14]:
#mengambil nilai yang terkandung dalam sebuah array multidimensional

print(nra[0,0])
print(nra[1,1])

1
3


In [13]:
#mengambil kolom pada index ke 0

nra[0,0:]

array([1, 2, 3])

In [14]:
#mengambil baris pada index ke 0

nra[0:3,0]

array([1, 2, 1])

In [15]:
#mereturn nilai pada sebuah array baru dengan nilai satu(ones) sesuai dengan dimensi yang di butuhkan

np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
##mereturn nilai pada sebuah array baru dengan nilai nol(zeros) sesuai dengan dimensi yang di butuhkan

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
#menampilkan array dengan type integer secara acak dengan nilai paling rendah 1 
#dan paling tinggi 5 pada dimensi(size) 3,3

np.random.randint(low=1, high=5, size=(3,3))

array([[3, 3, 4],
       [1, 2, 4],
       [4, 1, 1]])

In [18]:
#menampilkan array secara acak pada dimensi(size) 3,3

np.random.rand(3,3)

array([[0.40607619, 0.06762892, 0.86773718],
       [0.74051682, 0.67821112, 0.05869977],
       [0.3694236 , 0.08162416, 0.70717013]])

### pandas

In [15]:
#Membuat frame berbentuk tabel pada data yang ada 

index = [i+1 for i in range(10)]
latihan = np.random.randint(low=55, high=95, size=(10))
ujian = np.random.randint(low=35, high=65, size=(10))
data = {'Nomer':index, 'Latihan':latihan, 'Ujian':ujian}
df = pd.DataFrame(data)
df

Nomer  Latihan  Ujian
0      1       93     38
1      2       55     62
2      3       71     36
3      4       88     63
4      5       68     43
5      6       76     35
6      7       58     41
7      8       75     53
8      9       67     43
9     10       94     36

In [16]:
#mereturn n rows pertama pada sebuah frame, secara default n=5
df.head()

Nomer  Latihan  Ujian
0      1       93     38
1      2       55     62
2      3       71     36
3      4       88     63
4      5       68     43